"""empty message

Revision ID: 308e89ce3855
Revises: 0dd51dd6ef0f
Create Date: 2019-12-17 08:25:53.218906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308e89ce3855'
down_revision = '0dd51dd6ef0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description',
                                     sa.String(length=500), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent',
                                     sa.Boolean(), nullable=True, default=False))
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'genres',
                    existing_type=sa.VARCHAR(length=120),
                    nullable=False)
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
